### ISSUE TITLE
se requiere el instalador de la version de devexpress 23.1.3

### ISSUE THREAD

**Issue by hivanmeza** [davidvazquezpalestino/ERPPersonas#1]
se requiere el instalador o la liga de descarga para la vesion de devexpress 23.1.3 para poder compilar los ultimos cambios o bien la actualizacion de las dependencias del aplicativo a la nueva version de devexpress para que sea posible compilar

**Comment by davidvazquezpalestino** [comment]
https://drive.google.com/file/d/1-Me13rUCnEkA2ZHiHjX8vkn_jUvx-RQD/view?usp=sharing
